# Generated by Django 2.2.5 on 2021-05-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_bookedday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedday',
            options={'verbose_name': 'Booked Day', 'verbose_name_plural': 'Booked Days'},
        ),
    ]
